/**
 * Created by storm on 2017/5/5.
 */
export default {
    UPDATE_COLLAPSED: 'UPDATE_COLLAPSED',
    SEARCH_LINE: 'SEARCH_LINE',
    SEARCH_TG: 'SEARCH_TG',
    UPDATE_ANALYZE_METHOD: 'UPDATE_ANALYZE_METHOD',
    CLUSTERING: 'CLUSTERING',
    UPDATE_USER_TYPE: 'UPDATE_USER_TYPE',
    SEARCH_USER_IN_SHAPE: 'SEARCH_USER_IN_SHAPE',
    UPDATE_ALGORITHM: 'UPDATE_ALGORITHM',
    GET_TG_EQ: 'GET_TG_EQ'
};
